# Generated by Django 2.1.3 on 2018-12-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('pos', models.CharField(max_length=8)),
                ('age', models.FloatField()),
                ('tm', models.CharField(max_length=8)),
                ('g', models.IntegerField()),
                ('gs', models.IntegerField()),
                ('mp', models.FloatField()),
                ('fg', models.FloatField()),
                ('fga', models.FloatField()),
                ('fgp', models.FloatField()),
                ('threep', models.FloatField()),
                ('threepa', models.FloatField()),
                ('threepp', models.FloatField()),
                ('twop', models.FloatField()),
                ('twopa', models.FloatField()),
                ('twopp', models.FloatField()),
                ('ft', models.FloatField()),
                ('fta', models.FloatField()),
                ('ftp', models.FloatField()),
                ('orb', models.FloatField()),
                ('drb', models.FloatField()),
                ('trb', models.FloatField()),
                ('ast', models.FloatField()),
                ('stl', models.FloatField()),
                ('blk', models.FloatField()),
                ('tov', models.FloatField()),
                ('pf', models.FloatField()),
                ('pts', models.FloatField()),
            ],
            options={
                'verbose_name': 'nba',
                'verbose_name_plural': 'nba',
            },
        ),
    ]
